[Task 1]
esvault/formal-lang-course pull request #1
Opened 2022-09-11 15:56 UTC by esvault

2022-09-11 17:05 UTC, rustam-azimov commented
Пригласите, пожалуйста.

2022-09-11 17:53 UTC, rustam-azimov requested changes
Изменить тип возвращаемого значения и тест.

2022-09-11 17:53 UTC, rustam-azimov commented on project/graph.py
> +    return graph.number_of_nodes(), graph.number_of_edges(), s
Я бы советовал namedtuple использовать.

2022-09-11 17:53 UTC, rustam-azimov commented on tests/test_basic.py
> +    os.remove(filename)
Тут надо проверить что корректный файл создаётся и граф. Например сравнить с файлом созданным вручную.

2022-09-12 09:09 UTC, esvault commented on project/graph.py
> +    return graph.number_of_nodes(), graph.number_of_edges(), s
Done

2022-09-12 09:09 UTC, esvault commented on tests/test_basic.py
> +    os.remove(filename)
Done

2022-09-12 09:16 UTC, rustam-azimov approved these changes
Зачтено.

2022-09-12 16:03 UTC, merged