[Task 2]
esvault/formal-lang-course pull request #2
Opened 2022-09-18 11:30 UTC by esvault

2022-09-18 13:10 UTC, rustam-azimov requested changes

2022-09-18 13:10 UTC, rustam-azimov commented on tests/test_fa_utils.py
> +    assert len(automata.final_states) == 7
Хочется тестов следующего вида. Берем простой граф, по нему строим недетерминированный конечный автомат нашей функций и отдельно вручную строим НКА и сравниваем на эквивалентность. Или хотя бы что есть какие то строчки которые должен принимать и строчки которые не должен принимать, проверить это. Кроме того с разными наборами стартовых и конечных вершин попробовать.

2022-09-18 13:10 UTC, rustam-azimov commented on tests/test_fa_utils.py
> +    pattern = "abc|d"
можно побольше примеров и со звездой Клини. Кроме того тоже можно попроверять порождаются ли автоматом нужные строки и чтобы не порождались ненужные. Также проверка на минимальность может заключаться в том, что для простого выражения можно руками построить и сравнить на эквивалентность с тем автоматом, который возвращается функцией.

2022-09-18 17:38 UTC, rustam-azimov commented on project/fa_utils.py
> +    return eps_nfa.to_deterministic().minimize()
можно без to_deterministic(), посмотрите в документации

2022-09-19 09:41 UTC, esvault commented on tests/test_fa_utils.py
> +    pattern = "abc|d"
Done

2022-09-19 09:41 UTC, esvault commented on project/fa_utils.py
> +    return eps_nfa.to_deterministic().minimize()
Done

2022-09-19 09:44 UTC, esvault commented on tests/test_fa_utils.py
> +    assert len(automata.final_states) == 7
Done

2022-09-19 09:46 UTC, esvault commented on project/fa_utils.py
> +    return eps_nfa.to_deterministic().minimize()
А чем плох to_deterministic?

2022-09-19 14:35 UTC, rustam-azimov approved these changes
Зачтено

2022-09-19 16:31 UTC, merged