[Task 4]
esvault/formal-lang-course pull request #4
Opened 2022-10-04 12:30 UTC by esvault

2022-10-04 17:04 UTC, rustam-azimov requested changes

2022-10-04 17:04 UTC, rustam-azimov commented on project/rpq.py
> +    return result
Передаем граф, поэтому достижимые числа надо превратить в graph nodes.

2022-10-04 17:32 UTC, esvault commented on project/rpq.py
> +    return result
Вроде как числа и есть вершины графа.

2022-10-09 11:32 UTC, rustam-azimov commented on project/rpq.py
> +    return result
В общем случае вершины графа и индексы этих вершин могут не совпадать. Я пока зачту, но будьте готовы поддержать более общий случай, если это встретится в дальнейшем. Ну и в принципе тут можно было бы возвращать не числа, а честные объекты вершин графа, построенные по этим числам.

2022-10-09 11:32 UTC, rustam-azimov approved these changes

2022-10-14 09:41 UTC, merged