[Task7]
esvault/formal-lang-course pull request #8
Opened 2022-11-01 13:15 UTC by esvault

2022-11-02 15:42 UTC, rustam-azimov requested changes

2022-11-02 15:42 UTC, rustam-azimov commented on project/ecfg.py
> +    def ecfg_from_cfg(cls, cfg: CFG):
Надо добавить также возможность построения из файла, в идеале еще текстовой строки

2022-11-02 15:42 UTC, rustam-azimov commented on project/rsm.py
> +    def rsm_from_ecfg(cls, ecfg: ECFG) -> "RSM":
Тут тоже нужно уметь строит по ecfg  в виде файла или в виде строковой переменной. Я поздновато проверил, поэтому у Вас есть пара дней еще после жесткого дедлайна это все доделать.

2022-11-04 10:30 UTC, esvault commented on project/ecfg.py
> +    def ecfg_from_cfg(cls, cfg: CFG):
Добавил возможность построения из файла и строки

2022-11-04 10:30 UTC, esvault commented on project/rsm.py
> +    def rsm_from_ecfg(cls, ecfg: ECFG) -> "RSM":
Здесь можно будет передавать ecfg построенную из файла или строки

2022-11-04 16:04 UTC, rustam-azimov approved these changes
5 баллов

2022-11-04 16:14 UTC, merged